### ISSUE TITLE
Add a rule that flags use of "Drupal 8"

### ISSUE THREAD

**Issue by agentolivia** [OsioLabs/osiolabs-copyeditor#15]
We should add a rule that flags use of "Drupal 8" with a suggestion to use just "Drupal" if appropriate. It should be a warning and not an error (blocker), since sometimes it is appropriate to use Drupal 8 specifically.

https://trello.com/c/cPhwea8e/601-drupal-9-updates-q4

**Comment by agentolivia** [comment]
@eojthebrave Would this be something to add to https://github.com/OsioLabs/osiolabs-copyeditor/blob/master/styles/base/replacements.yml?

**Comment by eojthebrave** [comment]
@agentolivia yes, that would be a good place.
